version: 2

models:
  - name: flat_schema
    columns:
      - name: sale_id
        data_tests:
          - not_null
          - unique

      - name: customer_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id

      - name: product_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id

      - name: location_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_location')
                field: location_id