version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique

  - name: dim_products
    columns:
      - name: product_id
        data_tests:
          - not_null
          - unique

  - name: dim_location
    columns:
      - name: location_id
        data_tests:
          - not_null
          - unique